### ISSUE TITLE
newbie

### ISSUE THREAD

**Issue by cabriltt** [djansen1987/SAJeSolar#11]
Hi
I have just instaled a new SAJ h1 series in my home and i am trying to integrate in home assinstant with no luck.
I have a meter but i dont think i have a sec module.
After the configuration al the sensors have the state as unkown.
Can you help me?
Many thanks

**Comment by djansen1987** [comment]
continue on discussions at: [https://github.com/djansen1987/SAJeSolar/discussions/10](https://github.com/djansen1987/SAJeSolar/discussions/10)
