### ISSUE TITLE
Current House Load Power

### ISSUE THREAD

**Issue by BeardyBrah** [djansen1987/SAJeSolar#18]
Hi again @djansen1987,
Hoping to continue assisting with anything I'm finding from my end. I've noted I can't see a 'Current Home Load/Power' statistic to read how much the home is using throughout the day.

![homeloadpower](https://user-images.githubusercontent.com/66730427/144158861-872ade88-531c-4409-aaf5-46dfe3cd8c41.png)

a few unrelated finds;
sensor.esolar_solarpower should also have the suffix kWp.

sensor.esolar_gridpower doesn't seem to know if it's importing power or exporting power (in Watts). In either direction it reads as a positive number either way.

sensor.esolar_batterydirection has a number as a value, I've found -1 is Charging from PV, 1 means Discharging to home, 0 means standby/not currently being used. Can the value it outputs be changed to 'CHARGING / DISCHARGING / STANDBY' ?

Thanks mate! Love your work

**Comment by BeardyBrah** [comment]
Extra info that may help.

https://fop.saj-electric.com/saj/monitor/site/detailForm?plantuid=xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

```
pvPower: 54.00 #PV being generated
gridPower: 63.00 #feeding to grid realtime
inputOutputPower: 546.00 #dont know what this is
batteryPower: 1006.00 #battery discharging in W
totalLoadPower: 997.00 #real time home power usage
homeLoadPower: 550.00 #dont know what this is
backupLoadPower: 447.00 #dont know what this is
batCurr:19.50 #dont know what this is
batEnergyPercent: 28.00 #battery state of charge
pvDirection:1 #currently outputting
gridDirection:1 #currently exporting to grid
batteryDirection:1 #currently discharging
outPutDirection:1 #dont know what this is
```

![Screenshot 2021-12-01 184352](https://user-images.githubusercontent.com/66730427/144192418-73fc009a-ec01-4770-be3f-1521a16cd332.png)

**Comment by BeardyBrah** [comment]
Hey @djansen1987 
Can I be of any further assistance on this one? Need any extra information?

**Comment by djansen1987** [comment]
Hi @BeardyBrah, december has been a busy month. Hope to find time in januari to take a look at it

**Comment by djansen1987** [comment]
Hi @BeardyBrah,

Thanks for the enhancement and details below the answers:

>  I've noted I can't see a 'Current Home Load/Power' statistic to read how much the home is using throughout the day.

it was not added to the H1 module and is added in the upcoming update, add resource: totalLoadPower


> a few unrelated finds;
> sensor.esolar_solarpower should also have the suffix kWp.

For what i can find this is in Watt not in kWp

> sensor.esolar_gridpower doesn't seem to know if it's importing power or exporting power (in Watts). In either direction it reads as a positive number either way.

this can be known by the following sensor: outPutDirection
If i am correct in the esolar portal the number is also always positive. I understand your thoughts, for now not planning to change this.

> sensor.esolar_batterydirection has a number as a value, I've found -1 is Charging from PV, 1 means Discharging to home, 0 means standby/not currently being used. Can the value it outputs be changed to 'CHARGING / DISCHARGING / STANDBY' ?

Changed this in upcoming update 1.2.8

**Comment by djansen1987** [comment]
Hi @BeardyBrah

I was wondering if it is working for you and if i can close the issue ?

**Comment by BeardyBrah** [comment]
Hi mate,
Just saw this now. Heres what mine displays

![Screenshot 2022-01-15 083658](https://user-images.githubusercontent.com/66730427/149588512-820739c7-c256-4747-b6fe-280f11e76f62.png)

**Comment by BeardyBrah** [comment]
Updated my configuration.yaml to include totalLoadPower, fixed. Looking good

![Screenshot 2022-01-15 084151](https://user-images.githubusercontent.com/66730427/149589128-82b03c16-152b-4d93-b62f-20c449830fca.png)

**Comment by djansen1987** [comment]
Great! Thanks for pointing out! Have a great weekend!
