### ISSUE TITLE
Unit of measurement (warning) on sensor

### ISSUE THREAD

**Issue by BeardyBrah** [djansen1987/SAJeSolar#19]
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:158
Integration: Sensor (documentation, issues)
First occurred: December 7, 2021, 11:45:39 PM (1 occurrences)
Last logged: December 7, 2021, 11:45:39 PM

custom_components.saj_esolar.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.

**Comment by djansen1987** [comment]
Should be fixed in:
https://github.com/djansen1987/SAJeSolar/releases/tag/v1.2.7
