### ISSUE TITLE
Home Battery Storage (Energy Integration)

### ISSUE THREAD

**Issue by BeardyBrah** [djansen1987/SAJeSolar#21]
Hi Mate,
Thank you for the new updates. Your work is incredible. Happy to keep assisting in any way I can.

The final enhancement could be under the Energy Dashboard. The Home Battery Storage section allows to monitor battery Input & Output. 

![Screenshot 2022-01-15 090120](https://user-images.githubusercontent.com/66730427/149591445-3ef4601b-1bfc-4474-a727-ab3056b8b684.png)

Output via "sensor.esolar_batterypower" can't be selected.
I don't beleive we've found a method to read the input (yet...) I'll do some research and see if I can find something and report back

**Comment by djansen1987** [comment]
i think it must be these to:
![image](https://user-images.githubusercontent.com/20375973/149628370-9321baed-e930-49c6-9b5e-6bd6f23642fa.png)

I then need to know the parameters in the API and then find out which unit of measurement home assistant wants these in

**Comment by djansen1987** [comment]
Think these are the ones:
https://fop.saj-electric.com/saj/monitor/site/getPlantDetailChart2?plantuid=xxxxxxx
viewBean ->chargeElec
viewBean ->dischargeElec

**Comment by djansen1987** [comment]
Found them, created new release. Please let me know if it works for you ?

https://github.com/djansen1987/SAJeSolar/releases/tag/v1.2.9

**Comment by BeardyBrah** [comment]
Its reading something, however I don't think its the right value. 
Heres my SAJ Portal vs. HA readings
![Screenshot 2022-01-16 092623](https://user-images.githubusercontent.com/66730427/149639595-922f2ef2-5e84-49b1-9244-958455b5c647.png)
![Screenshot 2022-01-16 092647](https://user-images.githubusercontent.com/66730427/149639599-5fe975ea-1a91-4def-8706-4fa10f736299.png)

**Comment by djansen1987** [comment]
Are you able to look at the api level to see the values ? Could be Convert from watt to kwp over a longer term

**Comment by djansen1987** [comment]
Also look at the inverter view,there you can find the screenshot I taken. 

BTW energie dashboard needs kwp not watt if an correct for battery

**Comment by BeardyBrah** [comment]
few things I've found 

sensor.esolar_batterypower appears to read both the input (Charging) and the output (discharging) of the battery and can't dissern between the two. 

Same appears true for gridPower is the power im sending to the grid. This reflects sensor.esolar_gridpower but I have a feeling it reads both both input to the grid and consumption. Will report back on this one

Is it possible to code something along the lines of
IF batteryDirection = -1
THEN batteryPower = Charging
OUTPUT 1113 to esolar chargeElec (or a purpose built sensor)

IF batteryDirection = 1
THEN batteryPower = Discharging
OUTPUT x_amount to esolar dischargeElec (or again another sensor to read this value)

Same for Grid power I'd assume (if any of this makes any sense lol...I don't code)

![Screenshot 2022-01-16 095434](https://user-images.githubusercontent.com/66730427/149640193-8fc38cc8-2ea1-44d1-840a-c4a0ee861e62.png)
.

**Comment by BeardyBrah** [comment]
I've taken a look at the end of the day - I've highlighted everything that matches however can't seem to verify the daily of battery in/out.

![Screenshot 2022-01-16 212714](https://user-images.githubusercontent.com/66730427/149656300-a3affc75-a33f-49d8-949c-591b25904e03.png)

**Comment by djansen1987** [comment]
1. what if you go to: (inverter)
![image](https://user-images.githubusercontent.com/20375973/149727251-63147d79-8d68-48d2-bc9a-15edbbf8acf2.png)

2. then click on the module number:
![image](https://user-images.githubusercontent.com/20375973/149727353-6a704b16-a5f1-4394-8963-6d8e4b2ef578.png)

3. scroll down to the bottom of the page:
![image](https://user-images.githubusercontent.com/20375973/149727406-69b2e528-4056-46c9-a4e7-e1e12f88e666.png)

**Comment by BeardyBrah** [comment]
The statistic shows me an overall usage by the looks of it
Doesnt break it down over a 24 hour use

![Screenshot 2022-01-17 201412](https://user-images.githubusercontent.com/66730427/149741269-aaaa2f7f-10d5-449c-b690-d0cd57bc4b6c.png)

Having said that, the sensors you've found appear to be reading correctly (at a guess), heres todays usage.

14.9 kWh consumption in the home (total)
around 50% from solar directly
20 %'ish from the battery
30 %'ish from grid imports

![Screenshot 2022-01-17 201506](https://user-images.githubusercontent.com/66730427/149741570-ab619675-9e1a-4740-b493-500390d8cbac.png)

**Comment by djansen1987** [comment]
The home assistant Energy Dashboard takes the total, as this number should only increase it can there for know the usage over time by calculating it's first value and date/time and so on. Thanks for confirming!
