### ISSUE TITLE
Alarm number not being retrieved

### ISSUE THREAD

**Issue by Mr-Alicates** [djansen1987/SAJeSolar#26]
Hi!

I noticed today that the alarm count for my H1 inverter has been set as unknown for a few hours.

Everything else seems to be working fine.

Thanks!

**Comment by Mr-Alicates** [comment]
![Screenshot_20220613-165840](https://user-images.githubusercontent.com/25879760/173383774-dbcd53dd-c35b-4ab1-979e-6625ea3b60c1.png)

**Comment by djansen1987** [comment]
are there any error logs ?

**Comment by Mr-Alicates** [comment]
It seems that the number of alarms is no longer returned in the API call.

This is probably caused by a UI change by SAJ.

There is an "isAlarmed" field on that call that could be used instead.

**Comment by Mr-Alicates** [comment]
There aren't any error logs, the rest of fields are being retrieved like always

**Comment by djansen1987** [comment]
could you enable debug logging:
https://github.com/djansen1987/SAJeSolar#debugging

And send the JSON output to me by mail (do not post as it contains plantID etc)
github@djansen.nl

**Comment by Mr-Alicates** [comment]
Sure thing. 

I've added the log. Esolar seems to be down for maintenance right now though.

**Comment by Mr-Alicates** [comment]
Hey, I sent you the email. Any news on this?

**Comment by djansen1987** [comment]
Sorry have been very busy privately. Should be Fixed in the latest release:

https://github.com/djansen1987/SAJeSolar/releases/tag/v1.3.1

Please let me know if this fixes it for you?

**Comment by Mr-Alicates** [comment]
Thank you very much.

Works like a charm!

**Comment by djansen1987** [comment]
Thanks for your feedback!
