### ISSUE TITLE
supported devices: Greenheiss inverter GH-I

### ISSUE THREAD

**Issue by santiagozky** [djansen1987/SAJeSolar#33]
Hello,
Recently I had my solar installation done. I got an inverter "Greenheiss GH-I 2M STYLE". While investigating on it and how to read from it I discovered it is just a rebranded SAJ  R5 inverter for the spanish market.
Actually, my credentials from the monitoring site (http://inversores-style.greenheiss.com ) work perfectly in the SAJ esolar portal.
I installed this addone through HACS and I can report it works fine so far.

I think it would be useful to mention this. I cannot confirm for the other models but at least mine works fine.

**Comment by djansen1987** [comment]
Thanks for the Tip, will add it to the Readme
