### ISSUE TITLE
esolar nowPower En esolar todayElectricity

### ISSUE THREAD

**Issue by megapeer** [djansen1987/SAJeSolar#5]
De esolar nowPower blijft de volgende ochtend op 0 staan na herstart Home assistent werkt het weer.

in energie heb ik esolar todayElectricity  ingesteld bij de zonnepanelen 
De waarde is de volgende dag niet 0 en ik denk dat ie bij -10 of iets anders 
begint en gaat verder met optellen. Na herstart Home assistent telt de waarde af. Dit is alleen bij energie overzicht van Home Assistant 

omvormer gaat als de zon onder is uit en in de ochtend zelf weer aan

![E49912BD-AAB3-4385-B1EE-6655D67A9CBD](https://user-images.githubusercontent.com/70513178/129352097-8fc281a0-9fbe-44df-8e09-0af7ef7fa01a.jpeg)
![A6D46333-029E-4497-8280-38968998D4ED](https://user-images.githubusercontent.com/70513178/129352106-cd79d6de-78a3-432f-abdb-33e6b3cfb2ef.jpeg)
![717940F9-A95D-40AD-ABDF-4DC8C50841C9](https://user-images.githubusercontent.com/70513178/129352107-96693a67-b98c-4708-809c-79b5f8801a51.jpeg)

**Comment by megapeer** [comment]
![Uploading 92C6DFA9-CED2-47CA-A51D-3692A4808F43.jpeg…]()

**Comment by megapeer** [comment]
Dit overzicht is van gisteren 
![AD4B2039-BBB5-4918-A714-BF6F63D5F4E5](https://user-images.githubusercontent.com/70513178/129352756-fc7b101c-4290-43bd-8cd2-68480c354be1.jpeg)
![64C268E1-79E5-4896-84FB-68857F0E5B97](https://user-images.githubusercontent.com/70513178/129352762-ef633f45-151d-46d2-a3b1-7363f37f9955.jpeg)

**Comment by djansen1987** [comment]
Hi @megapeer 

Het lijkt er inderdaad op dat de API na een dag stopt met werken. Ik ben aan het werken aan een fix. Ik zie geen error's op dat moment op de API wat vreemd is, maar mijn vermoeden is dat er een cookie verlopen is. Als tijdelijke oplossing zou je een automation kunnen maken die s'nachts HA herstart (begrijp dat dat niet wenselijk is). Ik zal me best doen dit zo snel mogelijk op te lossen.

**Comment by djansen1987** [comment]
Should be fixed in V1.0.8: [https://github.com/djansen1987/SAJeSolar/releases/tag/v1.0.8](https://github.com/djansen1987/SAJeSolar/releases/tag/v1.0.8)

**Comment by megapeer** [comment]
helaas werkt het niet,

moest ha toch restarten vannochtend.

**Comment by megapeer** [comment]
Op Facebook zag ik iemand met zelfde probleem met andere omvormer, waarschijnlijk heb ik verkeerde sensor gekozen: esolar todayElectricity maar dat moet totaal zijn.

heb nu esolar totalElectricity ingesteld om te proberen en dat ziet er beter uit.

**Comment by djansen1987** [comment]
Bedankt voor de terug koppeling. Het is volgens mij belangrijk dat alle sensors over dezelfde tijdsbestek zijn. Dus allemaal today, month, year of total

**Comment by megapeer** [comment]
esolar nowPower en esolar todayElectricity blijven de volgende dag op 0 en moet ik ha herstarten en dan werkt het weer

**Comment by ruudleijnse** [comment]
It is striking that it does detect that the unit is on again after sunrise. Only then will it not update the data.
Maybe it's an idea to use that item to trigger a reload of the data, or cookie cleaning?

**Comment by djansen1987** [comment]
update: last week i was not able to work on the component. I will try to look in to it this week and hope to find an solution.

**Comment by djansen1987** [comment]
V1.2.1 did not yet fixed it. After another hard look, i was passing the wrong variable to the API to provide the clientdate.

This is now fixed in:
https://github.com/djansen1987/SAJeSolar/releases/tag/v1.2.2

**Comment by megapeer** [comment]
thanks, I am going to try

**Comment by djansen1987** [comment]
Thanks, received already a positive feedback from one of the users. Let me know if it also works for you after 24 hours

**Comment by megapeer** [comment]
thanks it works

**Comment by djansen1987** [comment]
That is great news! Lots and lots of time have gone in to it, so glad to hear it is solved!
