### ISSUE TITLE
Lettura non riuscita Aiuto!

### ISSUE THREAD

**Issue by Sendy16** [djansen1987/SAJeSolar#54]
Ciao sono Nuovo.
ho seguito tutto passo passo per un inverter   AS1-3kS-20.4
ma non leggo proprio tutto.
Qualcuno potrebbe darmi una mano?
![image](https://user-images.githubusercontent.com/126517621/221935598-51f4e281-c6f3-4d56-ba9b-7558560963e6.png)
![image](https://user-images.githubusercontent.com/126517621/221935922-43577991-97a0-42d6-b04c-25790922d110.png)

**Comment by Sendy16** [comment]
Scusate ma ci sono riuscito, avevo saltato il controllo H1

**Comment by djansen1987** [comment]
Great! have Fun using the intergration
