### ISSUE TITLE
more plants

### ISSUE THREAD

**Issue by erelke** [djansen1987/SAJeSolar#55]
Hi! Thanks for you work!

I have 2 plants with Saj inverters and AIO3 devices. How can monitor both?

If I specify the plant_id in configuration.yaml, I got this error:

`Invalid config for [sensor.saj_esolar]: [plant_id] is an invalid option for [sensor.saj_esolar]. Check: sensor.saj_esolar->plant_id. (See ?, line ?).`

If I remove the plant_id key, I get only the first plant. For me more important is the second. How can i monitor this?

**Comment by erelke** [comment]
"[plant_id] is an invalid option" error was because i used old version from hacs store. With latest version this error gone.
But still only one plant data is accessible.

**Comment by djansen1987** [comment]
I currently do not have time to investigate, maybe have a look at this fork of my intergration https://github.com/faanskit/ha-esolar
