### ISSUE TITLE
Peakpower not showing

### ISSUE THREAD

**Issue by JaySea77** [djansen1987/SAJeSolar#57]
I just updated this HA addon. I needed to remove the todayAlarmNum for it to work again. Though I notice that peakPower is not updating anymore and is showing as unknown right now. I have not removed that entry from the yaml.
Is this a known issue and is there a way to fix this on my end?

**Comment by djansen1987** [comment]
Hi @JaySea77,

Thanks for reporting! This has been fixed in the latest release: https://github.com/djansen1987/SAJeSolar/releases/tag/v1.4.4

**Comment by JaySea77** [comment]
Glad to help. I really love this extension
