### ISSUE TITLE
rename of resources and historical dashboard data

### ISSUE THREAD

**Issue by jgbar** [djansen1987/SAJeSolar#58]
Maby this is not the right place to ask, please tell me if so.

If i remember correctly renaming of entity_id or names (wich renaming the resources with last update(?)) used in a running/used dashboard means the loss of historical data of the entire dashboard and the sensor data of all sensors specified in the dashboard.

Will that be the case if i update to version 1.0.0.4 or later from version 1.0.0.3?

**Comment by djansen1987** [comment]
Hi @jgbar,

Are you sure you are on version 1.0.0.3 ? This is the first release from [Jul 16, 2021](https://github.com/djansen1987/SAJeSolar/releases/tag/v1.0.3).

Many release have come after, reading through them i can't see a reason why you would lose any history data. You can ofcourse first create a backup before updating so you can revert to it.

Also be sure to check your configuration YAML as this has changed of time and some sensors are deprecated.

Again i don't see any issues updating to the latest version, but never done such big step with updating the intergration. Good luck!
