### ISSUE TITLE
Add more states to runningState handling

### ISSUE THREAD

**Issue by elboletaire** [djansen1987/SAJeSolar#60]
For what I can see in the code, the state handling is binary: if it's zero it's shown as `off`, any other value is shown as `on`. In my case, I see I'm getting the state as `2` and, in the official SAJ portal, I can see the state as red. It doesn't mean it's not working, but there's some error connection in the inverter (a red color isn't a good UX for this case).

![imatge](https://user-images.githubusercontent.com/153305/235318292-3c17efc1-0417-4e12-8d63-eec457204cb0.png)
![imatge](https://user-images.githubusercontent.com/153305/235318299-e1e406aa-156b-459e-93dd-44a8bcdeef41.png)

I'm pretty newbie to homeassistant and, more specifically, to how plugins and sensors are done but, could it be possible to make it non binary? In this case, I'd show a "warning" text for this specific case.

**Comment by djansen1987** [comment]
Hi @elboletaire , what kind of device do you have? as there are multiple status values. also for example for accessories to converts

**Comment by elboletaire** [comment]
TBH I ended up modifying entirely the plugin on my own, but the change looks good, so I'll close the issue.

**Comment by djansen1987** [comment]
That is sad to hear, you could also do a PR to make the integration better for everyone. But thank you for the confirmation.

**Comment by elboletaire** [comment]
> That is sad to hear, you could also do a PR to make the integration better for everyone. But thank you for the confirmation.

Not sure my edits were worth adding... after doing many changes I realized I could had avoided doing changes by just creating aliases... If I were to do changes to the plugin I think I'd change it entirely, grouping sensors in a better way. But that's a lot of work and, as it is right now works for me, so.. 🤷🏼

**Comment by djansen1987** [comment]
I understand 👍 if you ever have some great additions let me know. I self do not use the integration my self an created it for a family member.  For him it is also working so any additions had low priority unleas added via PR
