### ISSUE TITLE
pvElec and useElec mulitplied by 1000?

### ISSUE THREAD

**Issue by Pierric82** [djansen1987/SAJeSolar#70]
Hi there!

I've been tracking my SAJ solar panels for some time now using this HA plugin, and I'm very thankful for it!

Today something happened... is it just for me? My pvElec and useElec sensors seem to have switched from kWh to Wh. To make this clear:
- previously, mid-morning I'd have seen something like pvElec = 2.5kWh because the plugin returns "2.5" and I set HA to use kWh as the unit -- consistent with all other sensors
- today I see a massive jump as my mid-morning production is pvElec = 2.5MWh - the plugin is returning "2500" and HA still considers that to be kWh
- some other related sensors (buyElec, sellElec) are still fine and correctly in the "single-digit kWh" range
- no change / incident is visible when using the SAJ web app, though I can't know that they didn't change conventions behind the scenes

Obviously if I now change the unit to Wh instead of kWh I'll get the right value, but the history is going to be affected (the unit affects all previous readings), and it won't be as consistent with other sensors.

My inverter is a SAJ R5-2K-S1-15.

EDIT: it's actually not a scale issue but a "base bump" one. It looks like those counters have jumped to 2.490 kWh this morning, and are now progressing "normally" on top of this base level.

Cheers,
Pierric.

**Comment by djansen1987** [comment]
Hi Pierric,

First of thanks for your message! I did not see it yet, but i do not use it myself anymore only a family relative. I will ask him. Could it be this happend after Home assistant updates ? (as they are also recently came out. )

**Comment by Pierric82** [comment]
Hi!
Thanks for your reply! I was just discussing the issue with my wife and she made me realise that contrary to my earlier assessment, the data in the official saj app is *not* fine, after all. The same crazy numbers appear there, I was just not looking in the right place earlier. So, I believe this fully clears home assistant and your (amazing) plugin. I'll wait to see if tomorrow's data (since those are daily counters) behaves better and if so I'll just try to clear the history of today from my home assistant and grafana databases.
Apologies for the confusion!
Pierric.
