### ISSUE TITLE
HA Energy Dashboard: which sensor do I add?

### ISSUE THREAD

**Issue by Argon007** [djansen1987/SAJeSolar#71]
Hi,

I've installed your integration: thanks for it! There is a sensor called "sensor.esolar_nowpower" which gives me the current Power that the Inverter generates. I tried to add this sensor to the HA Energy Dashboard (Solar Panels), but I can't see/select it in the list.

I see:
- esolar_buyelec
- esolar_chargeelec
- esolar_dischargeelec
- esolar_sellelec
- esolar_totalbuyelec
- esolar_totalbuyenergy
- esolar_totalloadenergy
- esolar_totalpvenergy
- esolar_totalsellelec
- esolar_totalsellenergy
- esolar_useelec

But none of them gives me the "current power" that I want to use in the Energy Dashboard. What am I missing or what am I doing wrong?

Thanks (a HA noob)!

**Comment by djansen1987** [comment]
Hi,

Great to hear! Please use the following from the documentation. Now power is not used in the energy dashboard

![image](https://github.com/djansen1987/SAJeSolar/assets/20375973/57f12fe0-ce95-4ead-8406-9855e774895c)
